In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
print(type(a))


<class 'numpy.ndarray'>


In [5]:
b=np.array([[1,2],[3,4]])

In [6]:
print(b)

[[1 2]
 [3 4]]


In [7]:
d=np.array([1,2,3,4],dtype=float)
print(d)

[1. 2. 3. 4.]


In [8]:
d=np.array([1,2,3,4],dtype=bool)
print(d)  #for all non zero value return true

[ True  True  True  True]


In [9]:
d=np.array([1,2,3,4],dtype=complex)
print(d)  

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.ones((3,4))#if we want to initialize

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.random.random((3,4))

array([[0.93442588, 0.22374292, 0.75817121, 0.50988588],
       [0.36590665, 0.7974459 , 0.75667469, 0.15614798],
       [0.79026793, 0.31124627, 0.83899698, 0.98563215]])

In [16]:
np.linspace(-10,10,10)#start end random10nums  linearly seperable 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [17]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

###Array Attributes

In [18]:
#ndim-number of dimension
a.ndim

1

In [19]:
#shape
b.shape

(2, 2)

In [20]:
b.size

4

In [21]:
b.itemsize

8

In [22]:
a.dtype

dtype('int64')

#Changing Datatype

In [23]:
a.dtype

dtype('int64')

In [24]:
a.astype(np.int32)

array([1, 2, 3, 4], dtype=int32)

#Array Operations 

In [25]:
a1=np.arange(1,7).reshape(2,3)
a2=np.arange(2,8).reshape(2,3)

In [26]:
#Scalar Operation 
#Arithmetic
a1*2
a1+2
a1/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [27]:
#Relational Operator
a2>=5

array([[False, False, False],
       [ True,  True,  True]])

In [28]:
#Vector Operations
#Arithmetic Operations
a1+a2

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [29]:
a1**a2

array([[     1,      8,     81],
       [  1024,  15625, 279936]])

#Array Functions

In [30]:
a1=np.random.random((2,3))
a1=np.round(a1*100)
a1

array([[77., 52., 91.],
       [66., 20., 21.]])

In [31]:
#min/max/sum/prod
#0->column and 1->row
np.max(a1,axis=1)

array([91., 66.])

In [32]:
np.max(a1)

np.float64(91.0)

In [33]:
np.mean(a1)

np.float64(54.5)

In [34]:
np.median(a1)

np.float64(59.0)

In [35]:
np.var(a1)

np.float64(714.9166666666666)

In [36]:
a1=np.arange(1,11).reshape(2,5)
a2=np.arange(1,11).reshape(5,2)

In [37]:
np.dot(a1,a2)

array([[ 95, 110],
       [220, 260]])

In [38]:
#log and exponent
np.log(a1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [39]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [40]:
#round/floor/cell
a1=np.array((1.3,2.9,3.1,4.5))
np.round(a1)

array([1., 3., 3., 4.])

In [41]:
np.ceil(a1)

array([2., 3., 4., 5.])

In [42]:
np.floor(a1)

array([1., 2., 3., 4.])

#Indexing and Slicing

In [43]:
a1=np.arange(10)
a2=np.arange(1,11).reshape(2,5)
a3=np.arange(1,7).reshape(3,2,1)

In [44]:
#last index
print(a1)
a1[-1]

[0 1 2 3 4 5 6 7 8 9]


np.int64(9)

In [45]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
#if i want item 6
a2[1,0]

np.int64(6)

In [47]:
a3

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [48]:
a3[1,1,0]

np.int64(4)

#Slicing

In [49]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a1[2:5]

array([2, 3, 4])

In [51]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
#if i want 0 th row and all columns
a2[0,:]

array([1, 2, 3, 4, 5])

In [53]:
#if i want 4 th column and all rows
a2[:,4]

array([ 5, 10])

In [54]:
a2[0:,1:3]

array([[2, 3],
       [7, 8]])

In [55]:
#if i want corener value
a2[::1,::4]


array([[ 1,  5],
       [ 6, 10]])

In [56]:
a2[::,1::2]

array([[2, 4],
       [7, 9]])

In [57]:
a2[1:,0::4]

array([[ 6, 10]])

In [58]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
a2[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [60]:
a1=np.arange(27).reshape(3,3,3)

In [61]:
a1


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
a1[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
a1[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
a1[0,1,:]

array([3, 4, 5])

In [65]:
a1[2,1:,1:3]

array([[22, 23],
       [25, 26]])

In [66]:
a1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [67]:
a1[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

#Iterating

In [68]:
a1=np.arange(11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [70]:
a=np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
for i in a:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [72]:
for i in np.nditer(a3): #firstly it convert into 1D array
    print(i)

1
2
3
4
5
6


#Reshaping

In [73]:
#reshape

In [74]:
#Transpose :it convert row to column and column to row
np.transpose(a3)

array([[[1, 3, 5],
        [2, 4, 6]]])

In [75]:
#ravel :it converts any that is 2D,3D,4D..in 1D array
a3.ravel()

array([1, 2, 3, 4, 5, 6])

#Stacking

In [76]:
x=np.arange(12).reshape(3,4)
y=np.arange(12,24).reshape(3,4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
y

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
np.hstack((x,y)) #for this size should same

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [79]:
np.vstack((x,y))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#spliting

In [81]:
#horizontal splitting
np.hsplit(x,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [87]:
np.vsplit(y,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]